export declare const Messages: {
    FEEDBACK_UPDATED: string;
    FEEDBACK_DELETED: string;
    FEEDBACK_CREATED: string;
    TECHNOLOGY_DELETED: string;
    TECHNOLOGY_UPDATED: string;
    TECHNOLOGY_CREATED: string;
    USER_DELETED: string;
    USER_CREATED: string;
};
export declare const Errors: {
    ADMIN_KEY_REQUIRED: string;
    ADMIN_POST_FEEDBACK: string;
    ADMIN_EDIT_FEEDBACK: string;
    ADMIN_DELETE_ADMIN: string;
    USER_NAME_REQUIRED: string;
    USER_ID_REQUIRED: string;
    USER_POST_OWN_FEEDBACK: string;
    USER_EDIT_OTHERS_FEEDBACK: string;
    DUPLICATE_USER_NAME: string;
    USER_NOT_FOUND: string;
    TECHNOLOGY_NAME_REQUIRED: string;
    TECHNOLOGY_DETAILS_REQUIRED: string;
    TECHNOLOGY_NOT_FOUND: string;
    FEEDBACK_NAME_REQUIRED: string;
    FEEDBACK_ID_REQUIRED: string;
    FEEDBACK_REQUIRED: string;
    FEEDBACK_STATUS_REQUIRED: string;
    FEEDBACK_STATUS_INCORRECT: string;
    FEEDBACK_EMPTY: string;
    FEEDBACK_NOT_FOUND: string;
    NAME_NOT_FOUND: string;
    DATE_FORMAT_INCORRECT: string;
    INTERNAL_ERROR: string;
    AUTHORIZATION_FAILED: string;
};
export declare function generateId(): string;
export declare function convertArrayToSet(arr: any): Set<unknown>;
export declare function convertStringToDate(date: string): Date | null;
